version: "3.8"
services:
  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 20s

  chroma:
    image: chromadb/chroma:latest
    container_name: chroma
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    container_name: symptom_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: symptom_chat
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: rag-api
    env_file:
      - ./api/.env
    ports:
      - "8088:8088"
    depends_on:
      ollama:
        condition: service_healthy
      chroma:
        condition: service_started
      redis:
        condition: service_started
      db:
        condition: service_started
    volumes:
      - ./api/app:/app/app
      - ./api/alembic:/app/alembic
      - ./api/alembic.ini:/app/alembic.ini
      - ./api/requirements.txt:/app/requirements.txt

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rag-frontend
    ports:
      - "5173:5173"
    depends_on:
      - api
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  ollama_data:
  chroma_data:
  postgres_data: